package com.thatwaz.dadjokes.notification

object NotificationDadJokes {
    // 👇 Put your 150 jokes here. I’ve seeded a handful as examples.
    // One-liners are fine; if you want setup/punchline, just include \n\n between them.
    val jokes: List<String> = listOf(
        "I ordered a chicken and an egg from Amazon.\n\nI'll let you know which comes first.",
        "Why don’t eggs tell jokes?\n\nThey’d crack each other up.",
        "Why did the math book look sad?\n\nIt had too many problems.",
        "I would tell you a joke about construction.\n\nBut I'm still working on it.",
        "I used to hate facial hair.\n\nBut then it grew on me.",
        "I’m on a seafood diet.\n\nI see food and I eat it.",
        "Why did the tomato turn red?\n\nIt saw the salad dressing.",
        "I used to play piano by ear.\n\nNow I use my hands.",
        "What do you call a belt made of watches?\n\nA waist of time.",
        "How does a penguin build its house?\n\nIgloos it together.",
        "Why can’t you trust stairs?\n\nThey’re always up to something.",
        "What do you call a fish wearing a bowtie?\n\nSofishticated.",
        "Why did the golfer bring two pairs of pants?\n\nIn case he got a hole in one.",
        "I told my computer I needed a break.\n\nNow it won’t stop sending me KitKats.",
        "Want to hear a joke about paper?\n\nNever mind, it’s tearable.",
        "What do you call a factory that makes okay products?\n\nA satisfactory.",
        "I used to be addicted to the hokey pokey.\n\nThen I turned myself around.",
        "Why don’t scientists trust atoms?\n\nBecause they make up everything.",
        "I don’t play soccer because I enjoy it.\n\nI do it for kicks.",
        "What do you call a pile of cats?\n\nA meowtain.",
        "I asked the librarian if the library had books on paranoia.\n\nShe whispered, 'They're right behind you.'",
        "Why did the cookie go to the hospital?\n\nBecause it felt crummy.",
        "I don’t trust those trees.\n\nThey seem kind of shady.",
        "What do you call an alligator in a vest?\n\nAn investigator.",
        "How do you organize a space party?\n\nYou planet.",
        "Why did the bicycle fall over?\n\nIt was two-tired.",
        "I asked my dog what's two minus two.\n\nHe said nothing.",
        "What do you call a can opener that doesn’t work?\n\nA can’t opener.",
        "I used to run a dating service for chickens.\n\nBut I was struggling to make hens meet.",
        "Why don’t oysters donate to charity?\n\nBecause they’re shellfish.",
        "I gave all my dead batteries away.\n\nFree of charge.",
        "What do you call a snowman with a six-pack?\n\nAn abdominal snowman.",
        "Why did the coffee file a police report?\n\nIt got mugged.",
        "I stayed up all night wondering where the sun went.\n\nThen it dawned on me.",
        "What do you call a bee that can’t make up its mind?\n\nA maybe.",
        "How does a cucumber become a pickle?\n\nIt goes through a jarring experience.",
        "I tried to catch fog yesterday.\n\nMist.",
        "What do you call a dinosaur with an extensive vocabulary?\n\nA thesaurus.",
        "Why did the orange stop rolling?\n\nIt ran out of juice.",
        "What do you call a sleeping bull?\n\nA bulldozer.",
        "How do you make a tissue dance?\n\nPut a little boogie in it.",
        "I’m reading a book on the history of glue.\n\nCan’t put it down.",
        "Why did the man fall down the well?\n\nBecause he couldn’t see that well.",
        "I tried to sue the airline for losing my luggage.\n\nI lost my case.",
        "What do you call a line of men waiting to get haircuts?\n\nA barber queue.",
        "Why did the photo go to jail?\n\nIt was framed.",
        "I told a joke about a roof.\n\nIt went over their heads.",
        "Why did the computer go to the doctor?\n\nIt had a virus.",
        "How do you find Will Smith in the snow?\n\nYou look for fresh prints.",
        "I bought a boat because it was on sail.",
        "Why was the math lecture so long?\n\nThe professor kept going off on a tangent.",
        "What did the buffalo say to his kid when he left for college?\n\nBison.",
        "I’m so good at sleeping.\n\nI can do it with my eyes closed.",
        "I asked a Frenchman if he played video games.\n\nHe said Wii.",
        "What do clouds wear under their clothes?\n\nThunderwear.",
        "Why did the scarecrow start a podcast?\n\nHe had a lot of corn-tent.",
        "Want to hear a joke about elevators?\n\nIt has its ups and downs.",
        "Why do cows wear bells?\n\nBecause their horns don’t work.",
        "I got a job at a bakery because I kneaded dough.",
        "What did the grape do when it got stepped on?\n\nIt let out a little whine.",
        "I’m reading a book about mazes.\n\nI got lost in it.",
        "What do you call a herd of sheep rolling down a hill?\n\nA lambslide.",
        "What did the janitor say when he jumped out of the closet?\n\nSupplies.",
        "I started a band called 999 Megabytes.\n\nWe still haven’t got a gig.",
        "Why did the stadium get hot after the game?\n\nAll the fans left.",
        "What’s orange and sounds like a parrot?\n\nA carrot.",
        "I ordered a book on puns.\n\nIt was a play on words.",
        "Why did the banana go to the doctor?\n\nIt wasn’t peeling well.",
        "I told my wife she should embrace her mistakes.\n\nShe gave me a hug.",
        "What do you call a magician who loses his magic?\n\nIan.",
        "Did you hear about the claustrophobic astronaut?\n\nHe just needed a little space.",
        "Why do chicken coops only have two doors?\n\nBecause if they had four, they’d be chicken sedans.",
        "I’m on a clock diet.\n\nI go back for seconds.",
        "What did the magician say to the fisherman?\n\nPick a cod, any cod.",
        "I told my friend ten puns to make him laugh.\n\nNo pun in ten did.",
        "Why did the computer show up at work late?\n\nIt had a hard drive.",
        "How do you fix a broken pumpkin?\n\nWith a pumpkin patch.",
        "I would tell you a joke about time travel.\n\nBut you didn’t like it.",
        "What do you call a sleeping dinosaur?\n\nA dino-snore.",
        "Why was the broom late?\n\nIt overswept.",
        "How do you make holy water?\n\nYou boil the heck out of it.",
        "I got hit in the head with a can of soda.\n\nThank goodness it was a soft drink.",
        "What do you call a dog magician?\n\nA labracadabrador.",
        "What do you call a nervous javelin thrower?\n\nShakes spear.",
        "I don’t trust calendars.\n\nTheir days are numbered.",
        "I used to be a banker.\n\nI lost interest.",
        "What do you call a boomerang that doesn’t come back?\n\nA stick.",
        "Why did the musician keep a ladder in the studio?\n\nTo reach the high notes.",
        "How does a turtle cross the road?\n\nShell by shell.",
        "What’s a pirate’s favorite letter?\n\nYou think it’s R, but it be the C.",
        "I once ate a clock.\n\nIt was very time-consuming.",
        "Why did the barber win the race?\n\nHe took a short cut.",
        "How do you organize your books?\n\nBy the shelf-abet.",
        "I bought some camouflage pants.\n\nBut I can’t find them.",
        "Why was the computer cold?\n\nIt left its Windows open.",
        "What do you call a fish with no eyes?\n\nFsh.",
        "Why did the music teacher go to jail?\n\nToo much treble.",
        "I started a gardening business.\n\nIt’s growing on me.",
        "What do you call a cow with no legs?\n\nGround beef.",
        "What do you call a cow with two legs?\n\nLean beef.",
        "What do you call a cow with all four legs?\n\nHigh steaks.",
        "How do you make a lemon drop?\n\nJust let it fall.",
        "I got a universal remote today.\n\nThis changes everything.",
        "How do you catch a squirrel?\n\nClimb a tree and act like a nut.",
        "Why did the hipster burn his tongue?\n\nHe drank his coffee before it was cool.",
        "I asked the gym instructor to teach me splits.\n\nHe asked how flexible I am. I said I can’t make Tuesdays.",
        "What do you call a parade of rabbits hopping backward?\n\nA receding hare-line.",
        "I would tell you a joke about chemistry.\n\nBut I don’t think I’d get a reaction.",
        "Why did the photo go to therapy?\n\nIt had too much exposure.",
        "I told my boss three companies were after me.\n\nGas, electric, and internet.",
        "What do you call a bear with no teeth?\n\nA gummy bear.",
        "Why can’t a nose be 12 inches long?\n\nBecause then it would be a foot.",
        "I used to work at a calendar factory.\n\nI got fired for taking a couple days off.",
        "I got a job at the orange juice factory.\n\nI got canned because I couldn’t concentrate.",
        "What do you call someone with no body and no nose?\n\nNobody knows.",
        "Why do golfers always carry a spare tee?\n\nFor good measure.",
        "I made a pencil with two erasers.\n\nIt was pointless.",
        "Did you hear about the restaurant on the moon?\n\nGreat food, no atmosphere.",
        "I started a story about a broken pencil.\n\nIt has no point.",
        "Why don’t skeletons play poker?\n\nThey don’t have the guts for high stakes.",
        "My wife told me I should do lunges to stay in shape.\n\nThat would be a big step forward.",
        "I used to think I was indecisive.\n\nNow I’m not so sure.",
        "I only trust 24 letters of the alphabet.\n\nI always have my doubts about y and z.",
        "What did the zero say to the eight?\n\nNice belt.",
        "I told a joke about a bed.\n\nIt hasn’t been made up yet.",
        "Why did the man put his money in the blender?\n\nHe wanted liquid assets.",
        "I’d tell you a joke about pizza.\n\nBut it’s a little cheesy.",
        "Why did the mushroom get invited to the party?\n\nBecause he’s a fungi.",
        "I’m writing a book on reverse psychology.\n\nPlease don’t read it.",
        "Why did the robber take a bath?\n\nHe wanted to make a clean getaway.",
        "I used to be a baker of pretzels.\n\nIt was a twisted career.",
        "Why did the scarecrow start a business?\n\nHe wanted to branch out.",
        "How do you tell if a vampire is sick?\n\nBy how much he is coffin.",
        "Why did the coach go to the bank?\n\nTo get his quarter back.",
        "Why did the picture go to art school?\n\nTo brush up on its skills.",
        "How do you fix a broken tomato?\n\nTomato paste.",
        "What do you call an elephant that doesn’t matter?\n\nAn irrelephant.",
        "Why did the baker go to therapy?\n\nHe had too much on his plate.",
        "What did the big flower say to the little flower?\n\nHi, bud.",
        "How does a vampire start a letter?\n\nTomb it may concern.",
        "I got a job at the mirror factory.\n\nI could really see myself there.",
        "Why did the snowman pick through a bag of carrots?\n\nHe was picking his nose.",
        "I tried to take a selfie with my coffee.\n\nIt was too latte.",
        "Why are fish so smart?\n\nThey live in schools.",
        "What do you call a frog with no back legs?\n\nUnhoppy.",
        "Why did the scarecrow refuse dessert?\n\nHe was stuffed.",
        "I told the wifi we needed to talk.\n\nIt said we needed more bandwidth.",
        "What do you call a bakery on the beach?\n\nA sand-wich shop.",
        "Why did the keyboard break up with the computer?\n\nToo many shifts.",
        "How do you keep a bagel from getting away?\n\nPut lox on it.",
        "What do you call a cow that just gave birth?\n\nDe-calf-inated.",
        "Why did the cookie cry?\n\nBecause its mom was a wafer so long.",
        "How do you stop a bull from charging?\n\nCancel its credit card.",
        "What do you call a deer with no eyes?\n\nNo idea.",
        "Why did the math teacher love the tree?\n\nIt had so many roots.",
        "What do you call cheese that can sing?\n\nBrie-oncé.",
        "Why did the bicycle need a kickstand?\n\nBecause it was two-tired of standing.",
        "How does the moon cut his hair?\n\nEclipse it.",
        "Why was the stadium so cool?\n\nIt was filled with fans.",
        "What do you call a potato wearing glasses?\n\nA spec-tater.",
        "Why did the scarecrow become a motivational speaker?\n\nHe was outstanding at standing out.",
        "How do you organize a scary party?\n\nYou plan-et of the ghouls.",
        "What do you call a sleeping pizza?\n\nA pi-zzz-a.",
        "Why did the belt get arrested?\n\nIt held up a pair of pants.",
        "What do you call a car that never stops?\n\nA cargo.",
        "Why did the smartphone go to school?\n\nIt wanted to be a little brighter.",
        "How do you make an octopus laugh?\n\nWith ten-tickles.",
        "Why did the broom get promoted?\n\nIt swept the competition.",
        "What do you call a cat that works at the bakery?\n\nA whisker.",
        "Why did the keyboard sleep well?\n\nIt had two good shifts.",
        "How do you turn soup into gold?\n\nAdd twenty-four carrots.",
        "Why did the musician bring a ladder to the concert?\n\nTo reach the high notes.",
        "What do you call a fish that practices medicine?\n\nA sturgeon.",
        "Why don’t some couples go to the gym?\n\nBecause some relationships don’t work out.",
        "What did the triangle say to the circle?\n\nYou’re pointless.",
        "Why did the charger cross the road?\n\nTo get to the other side of the outlet.",
        "How do you make a hot dog stand?\n\nTake away its chair.",
        "Why was the corn bad at making friends?\n\nIt was too corny.",
        "What do you call birds that stick together?\n\nVel-crows.",
        "Why did the scarecrow get good internet?\n\nHe found a great field of connection.",
        "How do you fix a broken jack-o-lantern?\n\nWith a pumpkin patch.",
        "Why did the calendar look nervous?\n\nIts days were numbered.",
        "What do you call a bear stuck in the rain?\n\nA drizzly bear.",
        "How do you get a squirrel to like you?\n\nAct like a nut.",
        "Why did the tomato sit down?\n\nIt ran out of juice.",
        "How do you make a tissue boat?\n\nPut a little sail in it.",
        "Why was the robot angry?\n\nSomeone kept pushing its buttons.",
        "What’s a computer’s favorite snack?\n\nMicrochips.",
        "Why did the scarecrow read books at night?\n\nHe wanted to be well red.",
        "How does a tree access the internet?\n\nIt logs on.",
        "Why did the barber bring crayons?\n\nTo draw a crowd.",
        "How do you keep a library warm?\n\nGive it more fans.",
        "Why was the photo embarrassed?\n\nIt was too negative.",
        "What do you call a dinosaur that crashes cars?\n\nTyrannosaurus wrecks.",
        "Why did the bicycle go to therapy?\n\nIt couldn’t handle the cycles."
    )

}
