package com.thatwaz.dadjokes.ui.sticklerz

object Quips {
    // === Banner ===
    val bannerLoaded = listOf(
        // existing ad-snark
        "Our sponsor insisted.", "Capitalism rectangle acquired.", "Ad loaded. Behave.",
        "Behold, the rectangle of revenue.", "Sponsored pixels detected.", "Ah yes, commerce.",
        "This keeps the dad jokes free(-ish).", "Please clap (quietly).", "Try not to stare directly at it.",
        "It pays for the punchlines.", "Ad’s here; act natural.", "Don’t worry, it’s housetrained.",
        "I bet my cat could use that!", "Is anyone working on the Y3K issue?",
        "Finally, a rectangle that believes in me.", "Ah yes, my next impulsive life choice.",
        "Bold of it to assume I have money.", "Put it on my imaginary credit card.",
        "This ad passed the vibe check. Barely.", "The prophecy foretold a rectangle.",
        "Adding to cart (spiritually).", "Economy: boosted. Wallet: ghosted.",
        "At last, a solution to problems I don’t have.", "New fear unlocked: targeted rectangles.",
        "I, too, identify as ‘limited-time offer’.", "Look, it’s capitalism in 1080p.",
        "Finally, something my toaster can’t run.", "This ad was raised by wolves.",
        "Clinically proven* (*by the ad).", "Now in flavors you can’t afford.",
        "I felt that in my subscription fatigue.", "May cause side effects like… shopping.",
        "Probably tax-deductible in Narnia.", "Recommended by 9/10 imaginary experts.",
        "Because your other apps weren’t judging you enough.", "Simply must-have, said the rectangle.",
        "It pairs well with poor decisions.", "Yes, I absolutely needed another hobby.",
        "Minimalist design. Maximalist price.", "Un-skippable in spirit.",
        "Finally, an ad that understands my chaos.", "Now with extra ‘upgrade to premium’ energy.",
        "I’ve seen less persistent pop-ups in folklore.", "Perfect for people who say ‘let’s circle back’.",
        "Certified fresh by the Council of Rectangles.", "Somewhere, a marketer just fist-pumped.",
        "My cat already added it to cart.", "Runs on vibes and microtransactions.",
        "It’s giving… ‘limited supply’.", "This is what my algorithms think of me.",
        "The rectangle demands attention.", "I’ll buy it when my plants start paying rent.",

        // NEW: your MST3K-style silly shower thoughts
        "Is soup just a drink with secrets?",
        "Are sandwiches just salads with trust issues?",
        "Is cereal just soup with better PR?",
        "Is coffee just bean soup with ambition?",
        "Do mirrors ever get tired of reflecting us?",
        "Do stairs ever get jealous of elevators?",
        "Do dogs think fetch is our cardio?",
        "If you jog backwards, do you gain time?",
        "If money doesn’t grow on trees, why do banks have branches?",
        "If silence is golden, why is it so awkward?",
        "Do clouds ever take a day off?",
        "Is dust just dirt’s retirement plan?",
        "Do penguins wear tuxedos, or do tuxedos wear penguins?",
        "If laughter adds years to your life, am I immortal yet?",
        "Do chickens ever look at scrambled eggs and think, \"that could’ve been me\"?",
        "If the early bird gets the worm, what does the lazy bird get—DoorDash?",
        "Do we park on driveways and drive on parkways just to confuse the aliens?",
        "If laughter is the best medicine, why don’t pharmacies sell jokes?",
        "When bread gets stale, does it feel crumby about itself?",
        "Do clouds ever gossip about the people they rain on?",
        "If money can’t buy happiness, why do candy bars cost $1.50?",
        "Are naps just free trial versions of sleep updates?",
        "Do cows think “moo” means something different in every language?",
        "If the universe is expanding, where’s it moving its furniture?",
        "When we say “sleep like a baby,” do we mean waking up every two hours crying?",
        "If ghosts walk through walls, do they trip on Wi-Fi?",
        "Do fish ever get thirsty, or are they just good at denial?",
        "If time heals all wounds, does it also cover dental?",
        "Why is it called a building if it’s already built?",
        "I asked my toaster for life advice—now I’m feeling burned.",
        "If cats have nine lives, do they pay nine rents?",
        "I’m not lazy, I’m just running on energy-saving mode.",
        "Passwords are like underwear—don’t share them and change them often.",
        "If the earth is 70% water, are we just soggy land croutons?",
        "They say money talks, but mine only says goodbye.",
        "If Wi-Fi is down, do we all just become Amish?",
        "My mirror and I aren’t on speaking terms—it keeps reflecting poorly on me.",
        "If a printer jams, does it get butter and toast too?",
        "I’m in a long-distance relationship with motivation—it never visits.",
        "They said “follow your dreams,” so I went back to bed."
    )


    val bannerFailed = listOf(
        "Ad ghosted us. Respect.", "No ad? Behold: free pixels.",
        "Even the sponsor needed a coffee.", "Budget went out for milk.",
        "Invisible ad—very premium.", "It’s buffering… in a parallel universe.",
        "Ad called in ‘meh’.", "Sponsored by silence™.",
        "The rectangle took a personal day.", "404: Capitalism not found.",
        "I guess we’re the content now.", "Marketing blinked first.",
        "Plot twist: we’re ad-free (for 10 seconds).", "Ad went to chase its KPIs.",
        "Paperwork said ‘come back later’.", "The economy unplugged itself."
    )

    // === Interstitial ===
    val interstitialReady = listOf(
        "The projector is warming up its capitalism reels.",
        "Please secure your popcorn; marketing turbulence ahead.",
        "Intermission approaching—stretch your sarcasm muscles.",
        "Trailers of commerce begin shortly. No autographs.",
        "A tasteful pause for the rectangle arts.",
        "Stand by: persuasion attempting to load charm module.",
        "Soon: a message from our rectangle overlords.",
        "We preheated the ad to 375° for optimal impressions.",
        "This break brought to you by ‘Probably Relevant, Maybe’.",
        "Brace for impact—of limited-time opinions.",
        "The lobby smells like metrics and nachos.",
        "Hold my root beer, I’m announcing capitalism.",
        "We’re buffering something shiny and budget-approved.",
        "A brief word from the Department of Urgent Wants.",
        "Hush now, the rectangle is practicing its vowels.",
        "Prepare your best nod-like-you-understand face.",
        "Incoming: an offer that thinks it’s destiny.",
        "Please refrain from adopting the ad as a lifestyle.",
        "We interrupt these groans for a fiscal moment.",
        "Marketing has entered the chat wearing sunglasses.",
        "Intermission: brought to you by the letter $ and the number ‘maybe’.",
        "Your patience will be rewarded with… opinions.",
        "Cue the soft jazz and assertive fonts.",
        "This rectangle trained for months to be two-dimensional.",
        "Please pet the ad with your eyes only.",
        "Thrilling previews of products you didn’t know existed.",
        "We’ve summoned a sponsored omen. It looks rectangular.",
        "Prepare to be gently influenced at medium heat.",
        "Take a deep breath. Inhale Helvetica. Exhale ROI.",
        "Oh good, the ad fairy has arrived.",
        "I was just thinking, “Could really use a car insurance quote right now.”",
        "Forget the jokes—bring on the detergent commercial.",
        "This app is great, but it’s missing… ads!",
        "Yes! A random ad, exactly what I tapped for.",
        "Please, interrupt my chuckle with your skincare routine.",
        "Finally, an ad about tractors—I don’t even farm.",
        "Perfect timing, I was about to be happy.",
        "Ah yes, a well-timed pause for yogurt.",
        "Nothing screams fun like 30 seconds of shampoo.",
        "Who needs jokes when we’ve got capitalism?",
        "I come for the ads, stay for the buffering.",
        "The only thing better than dad jokes is commercials.",
        "Just what I needed: unsolicited financial advice.",
        "Can we make the ads louder?",
        "I love being reminded I can’t afford things.",
        "Ads are like hugs from strangers: uncomfortable and unwanted.",
        "Of course I wanted an ad right now.",
        "Exactly why I opened this—trucks, not jokes.",
        "Nothing says “immersive experience” like car insurance mid-laugh.",
        "Forget the punchline, tell me about vitamins!",
        "I only open apps for the advertising experience.",
        "Every ad is like a tiny pop-up surprise party.",
        "Just what I wanted: to learn about soap mid-scroll.",
        "Mmm, ads—the seasoning of life."
    )

    val interstitialShown = listOf(
        "Remain calm. The rectangle is doing its ritual.",
        "Temporary capitalism storm—hold onto your popcorn.",
        "Please enjoy this scheduled stare at commerce.",
        "If overwhelmed, blink in Morse code.",
        "Do not adjust your sarcasm. We already did.",
        "Somewhere, a KPI just smiled.",
        "Sponsored eclipse in progress. Sunscreen optional.",
        "This rectangle claims it can change your life. Bold.",
        "We put the ‘ad’ in ‘adventure’ (legally distinct).",
        "I taught this rectangle to roll over. It monetized instead.",
        "Loading… opinions you didn’t know you had.",
        "Try focusing on the upper-left pixel. Meditative.",
        "The algorithm thinks this is your vibe. The algorithm is cheeky.",
        "My cat is taking notes for a purchase it won’t make.",
        "This message brought to you by rectangles who care (about metrics).",
        "Imagine elevator music, but ambitious.",
        "Behold: persuasion in 2D.",
        "We now pause reality for a word from the void.",
        "Please keep hands and feet inside the attention span.",
        "This ad has ambitions. I respect that.",
        "Scientifically engineered to be… present.",
        "Just nod like you’re learning something.",
        "Limited-time offer: your patience.",
        "The rectangle and I are in a staring contest.",
        "Pretend you’re reading a very tiny novel.",
        "It pairs nicely with existential dread.",
        "Somewhere, a marketer just whispered, ‘conversion’.",
        "The real MVP here is the skip button.",
        "Skip button? More like hope button.",
        "I was this close to laughing. Thanks, ad.",
        "I love how ads make me forget the joke.",
        "These ads are like speed bumps for my brain.",
        "Nothing like watching an ad to forget my problems.",
        "Ads: reminding me my time isn’t mine.",
        "A minute of ads for 5 seconds of joy—fair trade.",
        "Beautiful, I didn’t want to enjoy this app anyway.",
        "This is exactly why I quit cable TV.",
        "Oh, the sweet sound of monetization.",
        "Truly, the ad is the content.",
        "Wow, a 60-second ad for a 5-second joke.",
        "I’ll just sit here, fully invested in this random ad.",
        "Ads really add spice to my rage.",
        "Oh, thank you—I hate continuity anyway.",
        "The jokes are just filler between the ads.",
        "Ads: the true main character of every app.",
        "Nothing refreshes me like a break from fun.",
        "Keep the ads coming, my blood pressure isn’t high enough.",
        "I measure time in “ad breaks” now.",
        "I adore how every ad is louder than the jokes.",
        "Oh, an unskippable ad—my favorite flavor.",
        "Congratulations: you closed a rectangle.",
        "Welcome back. We kept your groans on pause.",
        "The intermission has left the chat.",
        "Plot resumed. Previously, on Dad Jokes…",
        "You survived with all major organs, including sarcasm.",
        "The economy thanks you for your patience.",
        "Achievement unlocked: Ad Escape Artist.",
        "And we’re clear—cue the punchlines.",
        "Your attention has returned from its sponsored vacation.",
        "Refreshments are imaginary; jokes are real.",
        "Back to low-budget comedy, high-budget puns.",
        "We now return to our regularly scheduled eye rolls.",
        "I filed the ad under ‘character development’.",
        "No spoilers, but the rectangle had a twist ending.",
        "Your seat warmed itself out of anxiety.",
        "Award for endurance: one (1) dad joke.",
        "Intermission over. Pretend nothing happened.",
        "Thanks for holding. Your pun will be with you shortly.",
        "Tell no one of what you saw. Or tell everyone.",
        "We tested your patience. It passed with a smirk.",
        "Rebooting humor subsystem… okay, it’s still dad jokes.",
        "Wallet status: unchanged. Spirit: slightly weirder.",
        "You lost 20 seconds, gained a story.",
        "The rectangle ascended. We remain.",
        "And now, a joke so good it almost pays rent.",
        "Resume groaning on my mark… groan."
    )

    val interstitialDismissed = listOf(
        "Congratulations: you closed a rectangle.",
        "Welcome back. We kept your groans on pause.",
        "The intermission has left the chat.",
        "Plot resumed. Previously, on Dad Jokes…",
        "You survived with all major organs, including sarcasm.",
        "The economy thanks you for your patience.",
        "Achievement unlocked: Ad Escape Artist.",
        "And we’re clear—cue the punchlines.",
        "Your attention has returned from its sponsored vacation.",
        "Refreshments are imaginary; jokes are real.",
        "Back to low-budget comedy, high-budget puns.",
        "We now return to our regularly scheduled eye rolls.",
        "I filed the ad under ‘character development’.",
        "No spoilers, but the rectangle had a twist ending.",
        "Your seat warmed itself out of anxiety.",
        "Award for endurance: one (1) dad joke.",
        "Intermission over. Pretend nothing happened.",
        "Thanks for holding. Your pun will be with you shortly.",
        "Tell no one of what you saw. Or tell everyone.",
        "We tested your patience. It passed with a smirk.",
        "Rebooting humor subsystem… okay, it’s still dad jokes.",
        "Wallet status: unchanged. Spirit: slightly weirder.",
        "You lost 20 seconds, gained a story.",
        "The rectangle ascended. We remain.",
        "And now, a joke so good it almost pays rent.",
        "Resume groaning on my mark… groan."
    )

    fun randomFor(mood: StickMood): String? = when (mood) {
        StickMood.BannerLoaded -> bannerLoaded.randomOrNull()
        StickMood.BannerFailed -> bannerFailed.randomOrNull()
        StickMood.InterstitialReady -> interstitialReady.randomOrNull()
        StickMood.InterstitialShown -> interstitialShown.randomOrNull()
        StickMood.InterstitialDismissed -> interstitialDismissed.randomOrNull()
        StickMood.Clicked, StickMood.Idle -> null
    }

    // In your existing Quips object
    fun poolFor(mood: StickMood): List<String> = when (mood) {
        StickMood.BannerLoaded          -> bannerLoaded
        StickMood.BannerFailed          -> bannerFailed
        StickMood.InterstitialReady     -> interstitialReady
        StickMood.InterstitialShown     -> interstitialShown
        StickMood.InterstitialDismissed -> interstitialDismissed
        else -> emptyList()
    }

}

private fun <T> List<T>.randomOrNull(): T? = if (isEmpty()) null else this.random()
